Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "bonusvm"
  config.vm.network "private_network", ip: "192.168.56.150"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 8192
  end

  config.vm.provision "shell", path: "scripts/install_tools.sh"
  config.vm.provision "shell", path: "scripts/install_k3d.sh"
  config.vm.provision "shell", path: "scripts/install_gitlab.sh"
end
